# 修改tomcat的端口
server:
  port: 8080

# 数据库连接配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.22.193.54:10001/yymhdb?useUnicode=true&amp;characterEncoding=utf-8;
    username: pgadmin
    password: 1qazXSW@

# 指定Mybatis中配置的映射文件的地址
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志输出级别输出
logging:
  level:
    com.example: debug
    org.springframework.transaction: debug
    org.springframework.jdbc: debug